// <auto-generated />
namespace FIT5032_PortfolioV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addDoBModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDoBModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202310080046325_addDoBModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
