// <auto-generated />
namespace FIT5032_PortfolioV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateModel4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateModel4));
        
        string IMigrationMetadata.Id
        {
            get { return "202310131144011_updateModel4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
