// <auto-generated />
namespace FIT5032_PortfolioV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixingAppointmentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixingAppointmentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202310101226398_fixingAppointmentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
